# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
  schedule:
  - cron: 50 4 * * *

permissions:
  contents: read

name: Semgrep
jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: semgrep/ci
    runs-on: ubuntu-24.04
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - run: semgrep ci --sarif > semgrep.sarif
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    # Upload SARIF file generated in previous step
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
      with:
        sarif_file: semgrep.sarif
      if: always()
